### ISSUE TITLE
NPE when saving player data

### ISSUE THREAD

**Issue by Jannyboy11** [Jannyboy11/InvSee-plus-plus#10]
Reported by discord user Neo8#4608:

```
22:25:29] [Server thread/INFO]: Produktecheck issued server command: /invsee Bene_Farmer5
[22:25:39] [Server thread/INFO]: TVW07 lost connection: Disconnected
[22:25:39] [Craft Scheduler Thread - 4197 - InvSeePlusPlus/ERROR]: [InvSee++] Error while saving offline inventory
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Loading entity NBT
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803) ~[?:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Airplane-48]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Airplane-48]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Airplane-48]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
    at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: net.minecraft.ReportedException: Loading entity NBT
    at net.minecraft.world.entity.Entity.load(Entity.java:2337) ~[patched_1.17.1.jar:git-Airplane-48]
    at com.janboerman.invsee.spigot.impl_1_17_1_R1.InvseeImpl.lambda$save$3(InvseeImpl.java:137) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
    ... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.isClientSide()" because "this.t" is null
    at net.minecraft.world.entity.LivingEntity.isCurrentlyGlowing(LivingEntity.java:4201) ~[?:?]
    at net.minecraft.world.entity.Entity.setGlowingTag(Entity.java:2877) ~[patched_1.17.1.jar:git-Airplane-48]
    at net.minecraft.world.entity.Entity.load(Entity.java:2224) ~[patched_1.17.1.jar:git-Airplane-48]
    at com.janboerman.invsee.spigot.impl_1_17_1_R1.InvseeImpl.lambda$save$3(InvseeImpl.java:137) ~[?:?]
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
    ... 6 more
```

**Comment by Jannyboy11** [comment]
Airplane is now discontinued server software.
