### ISSUE TITLE
Support for Paper 1.20.6

### ISSUE THREAD

**Issue by VibinHippo** [Jannyboy11/InvSee-plus-plus#104]
None of the Invsee++ .jar files (base, clear, give) work on Paper 1.20.6 (build #36). 
Is it possible to update them? 
Additionally, Paper changed the way plugins worked as of 1.20.5, which may be causing issues. 

---------------------------------------------------------------------------------
Error occurred while enabling InvSeePlusPlus v0.26.0 (Is it up to date?)
java.lang.RuntimeException: Paper version git-Paper-36 (MC: 1.20.6) is not supported by this release of InvSee++. Please use one of the following Paper versions: [1.20.2, 1.20.4]. Alternatively you can try upgrading InvSee++ if any of the versions listed here is older than your server's Minecraft version. InvSee++ is available on SpigotMC (recommended): https://www.spigotmc.org/resources/invsee.82342/ and on GitHub: https://github.com/Jannyboy11/InvSee-plus-plus/releases
        at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:37) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-36]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-36]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-36]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-36]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
----------------------------------------------------------------------------------

**Comment by Jannyboy11** [comment]
I'm working on it. I already prepared for the Paper changes, so once it works on CraftBukkit, it should already work on Paper too.

**Comment by Jannyboy11** [comment]
https://www.spigotmc.org/resources/invsee.82342/update?update=543314

**Comment by Jannyboy11** [comment]
> https://www.spigotmc.org/resources/invsee.82342/update?update=543314

This release also works on Paper.
