### ISSUE TITLE
Can't enable InvSeePlusPlus

### ISSUE THREAD

**Issue by LilithASMP** [Jannyboy11/InvSee-plus-plus#108]
[ERROR] [Minecraft] Error occurred while enabling InvSeePlusPlus v0.24.9 (Is it up to date?)
java.lang.ClassFormatError: Duplicate method name "m_150399_" with signature "(IILnet.minecraft.world.inventory.ClickType;Lnet.minecraft.world.entity.player.Player;)V" in class file com/janboerman/invsee/spigot/impl_1_20_1_R1/MainNmsContainer
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:240) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:143) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at com.janboerman.invsee.spigot.Impl_1_20_1.<init>(Setup.java:92) ~[?:?]
at com.janboerman.invsee.spigot.SetupImpl.lambda$static$7(Setup.java:133) ~[?:?]
at com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[?:?]
at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at com.mohistmc.plugins.pluginmanager.PluginManagers.reloadPluginCommand(PluginManagers.java:134) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at com.mohistmc.commands.PluginCommand.execute(PluginCommand.java:68) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:883) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.2.32-universal.jar%23859!/:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23146!/:?]
at net.minecraft.commands.Commands.m_242674_(Commands.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1873) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1837) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23854!/:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
[20:55:14]
[INFO] [com.janboerman.invsee.spigot.InvseePlusPlus] [InvSee++] Disabling InvSeePlusPlus v0.24.9

**Comment by Jannyboy11** [comment]
This is a bug in the plugin bytecode transformer of your server. Your server is not prepared to handle classes which define their own SRG-based methods in the source code. Please report this issue at the maintainers of your server software.
See https://github.com/kettingpowered/Ketting-1-20-x/issues/235 and https://github.com/MohistMC/Mohist/issues/2697.

Having said that: [this version](https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.24.8-Mohist-Arclight-1.20.1) of InvSee++ may work for you.
