### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by thiagogebrimm** [Jannyboy11/InvSee-plus-plus#11]
```
[22:39:26 INFO]: Nevisk issued server command: /invsee _kiochy
[22:39:26 WARN]: [InvSee++] Error reading player's save file: /home/container/./world/playerdata/9f68a2e5-dd54-3e1f-880a-8f27bb78b20f-6027909567927261037.dat
java.io.EOFException: null
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?]
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?]
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?]
        at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:50) ~[patched_1.17.1.jar:git-Purpur-1332]
        at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:34) ~[patched_1.17.1.jar:git-Purpur-1332]
        at com.janboerman.invsee.spigot.impl_1_17_1_R1.UUIDSearchSaveFilesStrategy.lambda$resolveUniqueId$1(UUIDSearchSaveFilesStrategy.java:54) ~[InvSee++.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Purpur-1332]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1332]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Jannyboy11** [comment]
An error is not necessarily a bug. The file reader couldn't read a player's save file, meaning that it's likely that it is corrupt. There's not much I can do about this.

**Comment by Jannyboy11** [comment]
The same issue is still present in 0.12.3:
```
27.07 10:51:08 [Server] INFO Red_Shaunia issued server command: /invseeplusplus:invsee loudskins
27.07 10:51:08 [Server] WARN [InvSee++] Error reading player's save file: /./world/playerdata/25cbc5d7-284a-47b9-93ec-e39212cbd4f7-949849349509887063.dat
27.07 10:51:08 [Server] INFO java.io.EOFException: null
27.07 10:51:08 [Server] INFO at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?]
27.07 10:51:08 [Server] INFO at net.minecraft.nbt.NbtIo.createDecompressorStream(NbtIo.java:49) ~[?:?]
27.07 10:51:08 [Server] INFO at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:53) ~[?:?]
27.07 10:51:08 [Server] INFO at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:33) ~[?:?]
27.07 10:51:08 [Server] INFO at com.janboerman.invsee.spigot.impl_1_19_R1.UUIDSearchSaveFilesStrategy.lambda$resolveUniqueId$1(UUIDSearchSaveFilesStrategy.java:53) ~[InvSee++.jar:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
27.07 10:51:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-62]
27.07 10:51:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-62]
27.07 10:51:08 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
27.07 10:51:08 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
27.07 10:51:08 [Server] ERROR [InvSee++] Error while trying to create main-inventory spectator inventory
27.07 10:51:08 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Loading NBT data
27.07 10:51:08 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
27.07 10:51:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-62]
27.07 10:51:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-62]
27.07 10:51:08 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
27.07 10:51:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
27.07 10:51:08 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I finally figured out a fix, so this will probably be resolved next week.

**Comment by Jankoekenpan** [comment]
Should be resolved as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/8dd76f920a9e16ce5f38484dec87512b5890cdd7.

**Comment by Jannyboy11** [comment]
If the plugin ever encounters the same error again, it really means the player save file is corrupted.
