### ISSUE TITLE
Plugin error in 1.21

### ISSUE THREAD

**Issue by matheeuslima** [Jannyboy11/InvSee-plus-plus#114]
[18:22:21 ERROR]: Error occurred while enabling InvSeePlusPlus v0.28.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Impl_1_21.<init>(Setup.java:105) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$9(Setup.java:130) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-14-e0d9d60]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Jannyboy11** [comment]
This is a bug in Paper; they didn't pull the patch which fixes this issue yet. This bug should be gone when Paper 1.21 is officially released. See https://github.com/Jannyboy11/InvSee-plus-plus/issues/110.

By the way, you wouldn't have run into this issue if you downloaded InvSee++ via PaperMC's plugin repository Hangar.
