### ISSUE TITLE
currently broken by/because of paper 1.21-dev

### ISSUE THREAD

**Issue by TauCubed** [Jannyboy11/InvSee-plus-plus#115]
Currently broken in paper due to paper fiddling with API stuff.

```[15:09:34 ERROR]: Error occurred while enabling InvSeePlusPlus v0.28.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Impl_1_21.<init>(Setup.java:105) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$9(Setup.java:130) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Not sure If I should report this to paper or you.

**Comment by Jannyboy11** [comment]
See: https://github.com/Jannyboy11/InvSee-plus-plus/issues/114
