### ISSUE TITLE
Exception during startup

### ISSUE THREAD

**Issue by FastJoe0** [Jannyboy11/InvSee-plus-plus#120]
I'm having trouble getting plugins to work on Paper 1.21

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[10:36:20 INFO]: [ReobfServer] Remapping server...
[10:36:23 INFO]: [ReobfServer] Done remapping server in 3697ms.
[10:36:23 INFO]: [PluginRemapper] Remapping plugin 'plugins\InvSeePlusPlus-Give-0.28.0.jar'...
[10:36:23 INFO]: [PluginRemapper] Remapping plugin 'plugins\InvSeePlusPlus-Clear-0.28.0.jar'...
[10:36:23 INFO]: [PluginRemapper] Remapping plugin 'plugins\InvSeePlusPlus-0.28.0.jar'...
[10:36:23 INFO]: [PluginRemapper] Done remapping plugin 'plugins\InvSeePlusPlus-Clear-0.28.0.jar' in 115ms.
[10:36:23 INFO]: [PluginRemapper] Done remapping plugin 'plugins\InvSeePlusPlus-Give-0.28.0.jar' in 132ms.
[10:36:24 INFO]: [PluginRemapper] Done remapping plugin 'plugins\InvSeePlusPlus-0.28.0.jar' in 265ms.
[10:36:29 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:36:31 INFO]: Loaded 1290 recipes
[10:36:32 INFO]: Loaded 1399 advancements
[10:36:32 INFO]: Starting minecraft server version 1.21
[10:36:32 INFO]: Loading properties
[10:36:32 INFO]: This server is running Paper version 1.21-39-master@aa8d38d (2024-06-29T09:10:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[10:36:32 INFO]: Server Ping Player Sample Count: 12
[10:36:32 INFO]: Using 4 threads for Netty based IO
[10:36:33 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[10:36:33 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 14 worker threads, and population gen parallelism of 14 threads
[10:36:33 INFO]: Default game type: SURVIVAL
[10:36:33 INFO]: Generating keypair
[10:36:33 INFO]: Starting Minecraft server on *:25565
[10:36:33 INFO]: Using default channel type
[10:36:33 INFO]: Paper: Using Java compression from Velocity.
[10:36:33 INFO]: Paper: Using Java cipher from Velocity.
[10:36:34 INFO]: [InvSee++] Loading server plugin InvSeePlusPlus v0.28.0
[10:36:34 INFO]: [InvSee++_Give] Loading server plugin InvSeePlusPlus_Give v0.28.0
[10:36:34 INFO]: [InvSee++_Clear] Loading server plugin InvSeePlusPlus_Clear v0.28.0
[10:36:34 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:36:34 INFO]: Preparing level "world"
[10:36:34 INFO]: Preparing start region for dimension minecraft:overworld
[10:36:35 INFO]: Time elapsed: 716 ms
[10:36:35 INFO]: Preparing start region for dimension minecraft:the_nether
[10:36:35 INFO]: Time elapsed: 62 ms
[10:36:35 INFO]: Preparing start region for dimension minecraft:the_end
[10:36:35 INFO]: Time elapsed: 47 ms
[10:36:35 INFO]: [InvSee++] Enabling InvSeePlusPlus v0.28.0
[10:36:35 ERROR]: Error occurred while enabling InvSeePlusPlus v0.28.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at InvSeePlusPlus-0.28.0.jar/com.janboerman.invsee.spigot.Impl_1_21.<init>(Setup.java:105) ~[InvSeePlusPlus-0.28.0.jar:?]
        at InvSeePlusPlus-0.28.0.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$9(Setup.java:130) ~[InvSeePlusPlus-0.28.0.jar:?]
        at InvSeePlusPlus-0.28.0.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[InvSeePlusPlus-0.28.0.jar:?]
        at InvSeePlusPlus-0.28.0.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[InvSeePlusPlus-0.28.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:36:35 INFO]: [InvSee++] Disabling InvSeePlusPlus v0.28.0
[10:36:36 INFO]: [InvSee++_Give] Enabling InvSeePlusPlus_Give v0.28.0
[10:36:36 ERROR]: Error occurred while enabling InvSeePlusPlus_Give v0.28.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/internal/version/ServerSoftware
        at InvSeePlusPlus-Give-0.28.0.jar/com.janboerman.invsee.spigot.addon.give.Setup.setup(Setup.java:13) ~[InvSeePlusPlus-Give-0.28.0.jar:?]
        at InvSeePlusPlus-Give-0.28.0.jar/com.janboerman.invsee.spigot.addon.give.GivePlugin.onEnable(GivePlugin.java:30) ~[InvSeePlusPlus-Give-0.28.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.janboerman.invsee.spigot.internal.version.ServerSoftware
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 14 more
[10:36:36 INFO]: [InvSee++_Give] Disabling InvSeePlusPlus_Give v0.28.0
[10:36:36 INFO]: [InvSee++_Clear] Enabling InvSeePlusPlus_Clear v0.28.0
[10:36:36 ERROR]: Error occurred while enabling InvSeePlusPlus_Clear v0.28.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/InvseePlusPlus
        at InvSeePlusPlus-Clear-0.28.0.jar/com.janboerman.invsee.spigot.addon.clear.ClearPlugin.onEnable(ClearPlugin.java:22) ~[InvSeePlusPlus-Clear-0.28.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.janboerman.invsee.spigot.InvseePlusPlus
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[10:36:36 INFO]: [InvSee++_Clear] Disabling InvSeePlusPlus_Clear v0.28.0
[10:36:36 INFO]: Running delayed init tasks
[10:36:36 INFO]: Done (3.786s)! For help, type "help"
[10:36:36 INFO]: Timings Reset
```

**Comment by Jannyboy11** [comment]
If a plugin works on Spigot but not on Paper, that should be considered a bug in Paper. Please report the issue at Paper, not here. You can refer them to #110.
