### ISSUE TITLE
Incompatible classchange (Purpur Server 1.20.6)

### ISSUE THREAD

**Issue by TheCiROMG** [Jannyboy11/InvSee-plus-plus#122]
`java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Impl_1_21.<init>(Setup.java:105) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$9(Setup.java:130) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Jannyboy11** [comment]
Title says Purpur 1.20.6 but it's actually 1.21.

**Comment by Jannyboy11** [comment]
If you can reproduce the same error on Spigot it's likely a bug in InvSee++. If you can't then it'a likely a bug in Purpur. Please see #110.
