### ISSUE TITLE
1.21.1 Console error

### ISSUE THREAD

**Issue by jurohn** [Jannyboy11/InvSee-plus-plus#124]
10.08 18:24:28 [Server] ERROR Error occurred while enabling InvSeePlusPlus_Give v0.29.0 (Is it up to date?)
10.08 18:24:28 [Server] INFO java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/internal/version/ServerSoftware
10.08 18:24:28 [Server] INFO at InvSee++_Give.jar/com.janboerman.invsee.spigot.addon.give.Setup.setup(Setup.java:13) ~[InvSee++_Give.jar:?]
10.08 18:24:28 [Server] INFO at InvSee++_Give.jar/com.janboerman.invsee.spigot.addon.give.GivePlugin.onEnable(GivePlugin.java:30) ~[InvSee++_Give.jar:?]
10.08 18:24:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:28 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:28 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:28 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
10.08 18:24:28 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.janboerman.invsee.spigot.internal.version.ServerSoftware
10.08 18:24:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:28 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
10.08 18:24:28 [Server] INFO ... 14 more

**Comment by FlamedDogo99** [comment]
If you refer to the [spigot page](https://www.spigotmc.org/resources/invsee.82342/), you'll see that the plugin doesn't currently support 1.21.1.
Also you're not even running the newest version of InvSee++? The current release is [v0.29.3](https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.29.3).
<details>
<summary>If you update to v0.29.3... </summary>
You should get this error instead

```
[21:23:27 ERROR]: Error occurred while enabling InvSeePlusPlus v0.29.3 (Is it up to date?)
java.lang.RuntimeException: Paper version 1.21.1-5-7d7f123 (MC: 1.21.1) is not supported by this release of InvSee++. Please use one of the following Paper versions: [1.20.1, 1.20.4, 1.20.6, 1.21]. Alternatively you can try upgrading InvSee++ if any of the versions listed here is older than your server's Minecraft version. InvSee++ is available on SpigotMC (recommended): https://www.spigotmc.org/resources/invsee.82342/ and on GitHub: https://github.com/Jannyboy11/InvSee-plus-plus/releases
	at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:37) ~[InvSee++.jar:?]
	at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:84) ~[InvSee++.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-5-7d7f123]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

</details>

Hope this helps.

**Comment by jurohn** [comment]
> If you refer to the [spigot page](https://www.spigotmc.org/resources/invsee.82342/), you'll see that the plugin doesn't currently support 1.21.1. Also you're not even running the newest version of InvSee++? The current release is [v0.29.3](https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.29.3).
> 
> If you update to v0.29.3...
> Hope this helps.

I didnt realise he didnt update his spigotmc page :) Thanks

**Comment by sgoleo2021** [comment]
Waiting for 1.21.1 support!

**Comment by Jannyboy11** [comment]
1.21.1 is now supported:
https://www.spigotmc.org/resources/invsee.82342/update?update=557351
