### ISSUE TITLE
0.11.1 conflicts with LuckPerms' Vault-Unsafe-Lookups option

### ISSUE THREAD

**Issue by D3dWiz** [Jannyboy11/InvSee-plus-plus#15]
I can turn off that option, but as it's said, I should do it as a last resort.

[03:39:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inventorysee' in plugin InvSeePlusPlus v0.11.1-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-103]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-103]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup a UUID for 'preslaw' (an offline player)

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUuid(LuckPermsVaultPermission.java:118) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:135) ~[?:?]
        at com.janboerman.invsee.spigot.api.Exempt.vaultHasPermission(Exempt.java:77) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.Exempt.canInventoryBeSpectated(Exempt.java:49) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.mainSpectatorInventory(InvseeAPI.java:222) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseeCommandExecutor.onCommand(InvseeCommandExecutor.java:92) ~[InvSee++.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more

**Comment by Jannyboy11** [comment]
Right. What is happening here is that InvSee++ is trying to check whether an offline player has the exempt permission (which prevent him/her from being spectated). To fix this I need to perform another UUID lookup. The code to do this is already in the plugin, so it's shouldn't take more than a day to implement this.
Thanks for the report!

**Comment by Jannyboy11** [comment]
Should be fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/bb0c91ca85daa9c0897ed1d0758eb92bf80f6bfe

**Comment by PaintsplattersMC** [comment]
Still an issue on 0.11.2

**Comment by Jannyboy11** [comment]
I had assumed LuckPerms would not support synchronous uuid lookups, but it also does not support synchronous permission lookups. This is not complying with the contract of Vault's Permission api, so technically this is a bug in LuckPerms.
I am however changing my code again to make the permission lookups themselves async too, so this scenario will not happen anymore.

**Comment by Jannyboy11** [comment]
https://github.com/Jannyboy11/InvSee-plus-plus/commit/6775528dfedfa8f4879c781d1b8d687c256321b3
