### ISSUE TITLE
Internal exception

### ISSUE THREAD

**Issue by YoYomec** [Jannyboy11/InvSee-plus-plus#17]
Hello,
I Have A problem
The server closes when I type /invsee <playername>.
I run my server on Aternos, with Mohist, in 1.16.5, with the 0.11.8 version of the plugin (mohist-1.16.5-963-universal.jar)
This is a crash report : https://mclo.gs/Xnn3JeQ

moreover, I see this when I open an endershest :
![image](https://user-images.githubusercontent.com/98414804/161371711-c340c407-439c-43d5-a70b-806166b9cca9.png)

**Comment by YoYomec** [comment]
And when I run the plugin on my computer with magma, there is an error message :
```
[14:38:00] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\InvSee++.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.janboerman.invsee.spigot.InvseePlusPlus'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[forge:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321] {}
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.janboerman.invsee.spigot.InvseePlusPlus
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:258) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:164) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:128) ~[forge:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_321] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_321] {}
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:96) ~[forge:?] {re:classloading}
        ... 8 more
Caused by: java.lang.UnsupportedClassVersionError: com/janboerman/invsee/spigot/InvseePlusPlus has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321] {}
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:251) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:164) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:128) ~[forge:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_321] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_321] {}
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:96) ~[forge:?] {re:classloading}
        ... 8 more
```

**Comment by Jannyboy11** [comment]
InvSee++ does not support Java 8, You need to be running on Java 11 or newer.

**Comment by Jannyboy11** [comment]
What's more: InvSee++ relies on the patched net.minecraft.server code from CraftBukkit. Mohist uses Forge's patches, and thus could be incompatible.
