### ISSUE TITLE
Crash on latest release w/ paper version

### ISSUE THREAD

**Issue by FireController1847** [Jannyboy11/InvSee-plus-plus#18]
Getting the following exception:
```
[22:24:15] [Server thread/INFO]: [InvSee++] Enabling InvSeePlusPlus v0.11.5-SNAPSHOT
[22:24:15] [Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus v0.11.5-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Unsupported server software. Please run on (a fork of) CraftBukkit.
	at com.janboerman.invsee.spigot.api.InvseeAPI.setup(InvseeAPI.java:163) ~[InvSee++-0.11.5.jar:?]
	at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:29) ~[InvSee++-0.11.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Running paper-1.18.2-318
Using 0.11.8
On 
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

**Comment by Jannyboy11** [comment]
You are running three versions behind. CraftBukkit 1.18.2 support was only added in InvSee++ v0.11.7.
Could you [download the latest version](https://www.spigotmc.org/resources/invsee.82342/download?version=444018) and try again please?

**Comment by FireController1847** [comment]
I'm so sorry. I was like I swore I downloaded the new version, checked my files and I disabled the new version's file and kept the old version instead of doing the reverse haha. My apologies for making this issue. Thank you for this wonderful plugin!

**Comment by Jannyboy11** [comment]
Thank you!
Do you think that this is a problem that more people could be having? Would it be helpful if I include the plugin's version in the file name? E.g. InvSee++-0.11.9.jar

**Comment by FireController1847** [comment]
I mean, I'd never complain about the version in the filename, it always does help in my opinion. Though I generally just put the version on myself (I have a naming scheme system I use for all my plugins to keep track of them).

As a developer I'm always for putting the version on, I tend to use the format Name-Version.jar (ex LevelHearts-2.1.0.jar). I also follow semver standards myself.

I don't think it's a problem many others will have, but it might be worth the small change if in the future it could potentially help?

Appreciate your quick responses and care for your plugin :)
