### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Brosweer** [Jannyboy11/InvSee-plus-plus#2]
When I start server, server write this exception:

[Server thread/ERROR]: Could not load 'plugins/InvSee++ (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/janboerman/invsee/spigot/InvseePlusPlus has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-390]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.UnsupportedClassVersionError: com/janboerman/invsee/spigot/InvseePlusPlus has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-390]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-390]
	... 7 more

**Comment by Jannyboy11** [comment]
Your server needs to run on Java 11 or newer in order to run this plugin. Java 11 has been the LTS release of Java for over two years now and it is well supported by all the large plugins. The Paper server implementation is even going to require it starting from Minecraft 1.17.
Downgrading to Java 8 is not an option for me, as it would require me to completely re-implement the client for mojang's rest-api, among some other things that can't easily be done. If you can't upgrade your Java, then I'd recomment you tell your host about it, or find another one which does offer Java 11. Alternatively you could fork the project and make it compatible again with Java 8, but I am not going to do this because I think it is useless busywork.
The README.md states that JDK-11 or newer is required for compiling, I will make it more clear that this dependency on Java 11 is also required for running the plugin.
