### ISSUE TITLE
a problem with the plugin :(

### ISSUE THREAD

**Issue by havikun** [Jannyboy11/InvSee-plus-plus#38]
### _**For some reason, the plugin doesn't let me open inventories of either online people or offline people. When I do it with someone who is online with the /invsee command, nothing appears in the chat and it doesn't open**_

[https://youtu.be/bmVtbhqfLp4](https://youtu.be/bmVtbhqfLp4)

[12:57:23] [Server thread/ERROR] [co.ja.in.sp.InvseePlusPlus/]: [InvSee++] Error while trying to create main-inventory spectator inventory
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'java.io.File net.minecraft.world.level.storage.PlayerDataStorage.getPlayerDir()'
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin,re:mixin}
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194) ~[?:?] {re:mixin,re:mixin}
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?] {re:mixin,re:mixin}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.resolveUUID(NamesAndUUIDs.java:182) ~[?:?] {}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.lambda$resolveUUID$6(NamesAndUUIDs.java:184) ~[?:?] {}
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?] {re:mixin,re:mixin}
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?] {re:mixin,re:mixin}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.resolveUUID(NamesAndUUIDs.java:182) ~[?:?] {}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.lambda$resolveUUID$6(NamesAndUUIDs.java:184) ~[?:?] {}
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?] {re:mixin,re:mixin}
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?] {re:mixin,re:mixin}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.resolveUUID(NamesAndUUIDs.java:182) ~[?:?] {}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.resolveUUID(NamesAndUUIDs.java:165) ~[?:?] {}
at com.janboerman.invsee.spigot.api.InvseeAPI.fetchUniqueId(InvseeAPI.java:240) ~[?:?] {}
at com.janboerman.invsee.spigot.api.InvseeAPI.mainSpectatorInventory(InvseeAPI.java:372) ~[?:?] {}
at com.janboerman.invsee.spigot.api.InvseeAPI.spectateInventory(InvseeAPI.java:330) ~[?:?] {}
at com.janboerman.invsee.spigot.InvseeCommandExecutor.onCommand(InvseeCommandExecutor.java:149) ~[?:?] {}
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge-1.18.2-40.2.0-universal.jar%23125!/:?] {re:mixin,re:mixin,re:classloading}
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[forge-1.18.2-40.2.0-universal.jar%23125!/:?] {re:classloading}
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:776) ~[forge-1.18.2-40.2.0-universal.jar%23125!/:7e29f765-296df566-9fb885e8] {re:classloading}
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1647) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1578) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1560) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:6) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:26) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,re:mixin}
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,re:computing_frames,re:classloading}
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1022) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:133) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1005) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:999) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:985) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:884) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:257) ~[server-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.NoSuchMethodError: 'java.io.File net.minecraft.world.level.storage.PlayerDataStorage.getPlayerDir()'
at com.janboerman.invsee.spigot.impl_1_18_2_R2.UUIDSearchSaveFilesStrategy.resolveUniqueId(UUIDSearchSaveFilesStrategy.java:46) ~[?:?] {}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.resolveUUID(NamesAndUUIDs.java:182) ~[?:?] {}
at com.janboerman.invsee.spigot.internal.NamesAndUUIDs.lambda$resolveUUID$6(NamesAndUUIDs.java:184) ~[?:?] {}
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?] {re:mixin,re:mixin}
... 37 more

-

**Comment by Jannyboy11** [comment]
You're running hybrid server software that supports both plugins and mods, but does not have all of CraftBukkit patches. I need to know which server software it is before I can help you any further.

**Comment by havikun** [comment]
the server software is the magma foundation, now I will download the 0.18.1 plugin to see if it works

**Comment by havikun** [comment]
It still doesn't work having downloaded the 0.18.1 release, and now it doesn't even leave me a message that there was an error trying to open the inventory

**Comment by Jannyboy11** [comment]
Alright, thanks for telling me!

I had the following conversation on the Magma discord:
![image](https://user-images.githubusercontent.com/5656370/215538918-9619d5e1-731b-4058-a6d9-242ee35c2e12.png)

The issue should be fixed as of [Release v0.18.2](https://github.com/Jannyboy11/Invsee-Plus-Plus/releases/v0.18.2), otherwise, it will be fixed by a future version of Magma.

**Comment by Jannyboy11** [comment]
> otherwise, it will be fixed by a future version of Magma.

Magma added this functionality as of https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/commit/f7c89f3a388a1d7ff076fb5b5ff63bb89e6f8e33, which is included in the next release of Magma, which is currently underway!

**Comment by havikun** [comment]
oh, thank you very much!, I'll try now with version 0.18.2, if it doesn't work, I'll wait for the next versions of magma, now I'll try and see how it goes

**Comment by Jannyboy11** [comment]
Hmmm. For me it works in online mode, but not in offline mode (which I think is what you're using as well). I will have to do some more investigation.

**Comment by Jannyboy11** [comment]
Re-added the bug-in-other-software label since the 'getting the player files'-bug is now fixed, but there is a different bug now.

**Comment by havikun** [comment]
mmmm I understand, thank you so much for the help, so, I need to wait for the new version of magma? I could test if it goes in online mode ^^

**Comment by Jannyboy11** [comment]
I tested in both online and offline mode. It doesn't work in either mode.

**Comment by havikun** [comment]
Don't worry, I'll be attentive to anything, thank you very much for the help and kindness :D

**Comment by Jannyboy11** [comment]
Okay, I did some more investigation and here is what I found: The technique that InvSee++ uses to open an inventory with a custom title and mirror **per spectator** works on CraftBukkit, but does not work on Magma. I am not sure whether this is technically a **bug** in Magma (since using internals actually isn't stable api), so I will find a fix for this for Magma.

**Comment by Jannyboy11** [comment]
Fixed as of [Release 0.18.3](https://github.com/Jannyboy11/Invsee-Plus-Plus/releases/v0.18.3). I had no issues anymore on Magma using this build.
Could you close the issue when it works for you as well?

**Comment by havikun** [comment]
hello, I'm going to see if it works with version 0.18.3, I'll let you know in a few minutes :D

**Comment by havikun** [comment]
![image](https://user-images.githubusercontent.com/123825280/216210502-794dfab8-8418-45b6-b39e-b2644aa6f06c.png)

hey, now the plugin works perfectly for me, thank you very much for your patience hahaha, now I'm going to close the issue :D

**Comment by YassevZriona** [comment]
JannyBoy, im just commenting - you are such a nice guy
I was just checking out this issue since Im on hybrid too but wow
usually plugin developers hate hybrid users
You are really friendly and I like that :D

You are a nice guy and I hope you will experience nice things in your life...
@Jannyboy11

**Comment by Jannyboy11** [comment]
> JannyBoy, im just commenting - you are such a nice guy

Thank you!

> I was just checking out this issue since Im on hybrid too but wow usually plugin developers hate hybrid users You are really friendly and I like that :D

Yes I understand why other plugin developers do not support hybrid servers: For large plugins hybrid server support costs a lot of effort, and the gain is very small for them, because hybrid servers are only a really small percentage of users. InvSee++ is rather small, so for me it wasn't too much effort.

> You are a nice guy and I hope you will experience nice things in your life... @Jannyboy11

Thanks! I recently got my masters degree in computer science, so good things are definitely happining!
