### ISSUE TITLE
String formatting problem

### ISSUE THREAD

**Issue by Jannyboy11** [Jannyboy11/InvSee-plus-plus#39]
Reported by Discord user Foxculated#5051:

```
[09:20:34] [Server thread/INFO]: PiLightSpeed issued server command: /invsee .Tag_Oggy_op
[09:20:34] [Craft Scheduler Thread - 42 - InteractiveChat/INFO]: OgNeTwOrK Warrior .SS_GAMING_OG ➟ 1 hi h mere pass ab
[09:20:34] [Server thread/INFO]: .FireCorn572428 issued server command: /msg ss mera elytra??
[09:20:40] [Server thread/INFO]: .MCPE6079 issued server command: /msg jack can u tp me in stonghold
[09:20:41] [Server thread/ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInCloseWindow@70a9e640 for PiLightSpeed
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4438) ~[?:?]
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3176) ~[?:?]
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3134) ~[?:?]
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2896) ~[?:?]
	at java.util.Formatter.parse(Formatter.java:2747) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at com.janboerman.invsee.spigot.api.logging.LogOutputImpl$DiffFormattable.formatTo(LogOutput.java:210) ~[InvSee++.jar:?]
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:3049) ~[?:?]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2933) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2695) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at com.janboerman.invsee.spigot.api.logging.Action.formatTo(Action.java:34) ~[InvSee++.jar:?]
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:3049) ~[?:?]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2933) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2689) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
	at java.lang.String.format(String.java:4143) ~[?:?]
	at com.janboerman.invsee.spigot.api.logging.LogOutputImpl.log(LogOutput.java:166) ~[InvSee++.jar:?]
	at com.janboerman.invsee.spigot.api.logging.DifferenceTracker.onClose(DifferenceTracker.java:35) ~[InvSee++.jar:?]
	at com.janboerman.invsee.spigot.impl_1_19_3_R2.MainNmsContainer.b(MainNmsContainer.java:89) ~[InvSee++.jar:?]
	at net.minecraft.server.level.ServerPlayer.doCloseContainer(ServerPlayer.java:1689) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3020) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3011) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1905]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The config contains no logging settings.

**Comment by Jannyboy11** [comment]
Fixed as per https://github.com/Jannyboy11/InvSee-plus-plus/commit/f6ea899204a5582000fbbe906c4a015c31ce0b22#diff-a1372e75245496a1f1cbc2dfa98e6b3c506735137940b3c6c63a73b7ed29a34aR207
