### ISSUE TITLE
Error detected

### ISSUE THREAD

**Issue by thiagogebrim13** [Jannyboy11/InvSee-plus-plus#4]
```
[13:43:54 ERROR]: [InvSee++] Error while trying to create ender-chest spectator inventory
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class com.janboerman.invsee.spigot.impl_1_17_R1.FakeEntityHuman does not define or inherit an implementation of the resolved method 'abstract void initAttributes()' of abstract class net.minecraft.world.entity.EntityLiving.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Purpur-1174]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Purpur-1174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Purpur-1174]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.janboerman.invsee.spigot.impl_1_17_R1.FakeEntityHuman does not define or inherit an implementation of the resolved method 'abstract void initAttributes()' of abstract class net.minecraft.world.entity.EntityLiving.
        at net.minecraft.world.entity.EntityLiving.<init>(EntityLiving.java:294) ~[patched_1.17.jar:git-Purpur-1174]
        at net.minecraft.world.entity.player.EntityHuman.<init>(EntityHuman.java:221) ~[patched_1.17.jar:git-Purpur-1174]
        at com.janboerman.invsee.spigot.impl_1_17_R1.FakeEntityHuman.<init>(FakeEntityHuman.java:12) ~[?:?]
        at com.janboerman.invsee.spigot.impl_1_17_R1.InvseeImpl.createOffline(InvseeImpl.java:106) ~[?:?]
        at com.janboerman.invsee.spigot.impl_1_17_R1.InvseeImpl.createOfflineEnderChest(InvseeImpl.java:84) ~[?:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.spectateEnderChest(InvseeAPI.java:412) ~[?:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.lambda$spectateEnderChest$17(InvseeAPI.java:377) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        ... 8 more
```

**Comment by Jannyboy11** [comment]
It seems that Purpur yet again is breaking behaviour from CraftBukkit. This is caused by Purpur's configurable base attributes patch. I can make this error go away now, but this might mean that in the future this setting from purpur will be ignored in the edge case when spectating an inventory of a player who has not logged in yet.

**Comment by Jannyboy11** [comment]
Looking at Purpur's commit history this issue already got a fix 15 hours ago: https://github.com/pl3xgaming/Purpur/commit/fb509120d80d3d6b62b595dc6a7b3ed36e42776f#diff-71175e3ab01cc6f91103d949949c0acea62f11fb6ba9d16d5693a5b19b62b9fe
I can't compile Purpur at the moment so could you try again on the latest version of Purpur and confirm that the error is no longer there? Feel free to close the issue then.

**Comment by thiagogebrim13** [comment]
Sorted out
