### ISSUE TITLE
Cannot execute command 'invsee' in plugin InvSeePlusPlus v0.19.7-SNAPSHOT - plugin is disabled. (Purpur)

### ISSUE THREAD

**Issue by GameTec-live** [Jannyboy11/InvSee-plus-plus#41]
Im running invsee++ plus both addons on purpur (git-Purpur-1666 (MC: 1.19)), Java 17 (openjdk 17.0.6 2023-01-17) on ubuntu server (20.04.5 LTS) and getting the following error when trying to run a invsee:

```
[20:07:13] [Server thread/INFO]: GameTec_live issued server command: /invsee GameTec_live
[20:07:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'invsee' in plugin InvSeePlusPlus v0.19.7-SNAPSHOT - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2459) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1433) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1666]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:07:15] [User Authenticator #1/INFO]: UUID of player [REDACTED] is [REDACTED]
[20:07:16] [Server thread/INFO]: [REDACTED] joined the game
[20:07:16] [Server thread/INFO]: [REDACTED][/[REDACTED]] logged in with entity id [REDACTED] at ([world][REDACTED])
[20:07:18] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5007ms or 100 ticks behind
[20:07:18] [Server thread/INFO]: GameTec_live issued server command: /invsee [REDACTED]
[20:07:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'invsee' in plugin InvSeePlusPlus v0.19.7-SNAPSHOT - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2459) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1433) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1666]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1666]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:07:33] [User Authenticator #1/INFO]: UUID of player [REDACTED] is [REDACTED]
```
Any help is welcome! Plugin looks neat tho....

**Comment by Jannyboy11** [comment]
The latest version of InvSee++ that supports Minecraft 1.19 is version 0.15.2. The plugin should have reported the versions it supports when the server started.
You can remedy this issue by downgrading InvSee++ to version 0.15.2, or you can upgrade your server to Minecraft version 1.19.3 or 1.19.4.

**Comment by Jannyboy11** [comment]
https://github.com/Jannyboy11/InvSee-plus-plus#supported-server-software
