### ISSUE TITLE
Problems on start up with Paper 1.19.4

### ISSUE THREAD

**Issue by dgal1992** [Jannyboy11/InvSee-plus-plus#47]
Having issues starting up using Paper Spigot (v159). Unsure whether this is a InvSee or Paper issue. 

From a quick glance it seems that the versions are conflicting. Happy for this to be closed if it's a paper problem.

`[10:50:06] [Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus v0.21.2-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Specified map is empty
        at java.util.EnumMap.<init>(EnumMap.java:174) ~[?:?]
        at com.janboerman.invsee.spigot.api.logging.LogOptions.<init>(LogOptions.java:47) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.logging.LogOptions.clone(LogOptions.java:98) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.setLogOptions(InvseeAPI.java:209) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:117) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-519]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-519]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:50:06] [Server thread/INFO]: [InvSee++] Disabling InvSeePlusPlus v0.21.2-SNAPSHOT
[10:50:06] [Server thread/INFO]: [DiscordSRV] Enabling DiscordSRV v1.26.2
[10:50:06] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.1.0-SNAPSHOT
[10:50:06] [Server thread/INFO]: [InvSee++_Clear] Enabling InvSeePlusPlus_Clear v0.21.2-SNAPSHOT
[10:50:06] [Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus_Clear v0.21.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/InvseePlusPlus
        at com.janboerman.invsee.spigot.addon.clear.ClearPlugin.onEnable(ClearPlugin.java:22) ~[InvSee++_Clear.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-519]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-519]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.janboerman.invsee.spigot.InvseePlusPlus
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[10:50:06] [Server thread/INFO]: [InvSee++_Clear] Disabling InvSeePlusPlus_Clear v0.21.2-SNAPSHOT
[10:50:06] [Server thread/INFO]: [InvSee++_Give] Enabling InvSeePlusPlus_Give v0.21.2-SNAPSHOT
[10:50:06] [Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus_Give v0.21.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/internal/MappingsVersion
        at com.janboerman.invsee.spigot.addon.give.Setup.setup(Setup.java:44) ~[InvSee++_Give.jar:?]
        at com.janboerman.invsee.spigot.addon.give.GivePlugin.onEnable(GivePlugin.java:30) ~[InvSee++_Give.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-519]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-519]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.janboerman.invsee.spigot.internal.MappingsVersion
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more`

**Comment by Jannyboy11** [comment]
Fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/releases/v0.21.4. I was also able to load both InvSeePlusPlus and InvSeePlusPlug_Give on the latest version of Paper, so be sure to update your server. If it works for you after updating, could you close this issue? Thanks!

**Comment by dgal1992** [comment]
Works fine with latest Spigot & paper versions as of 1.19.4. Closing off now
