### ISSUE TITLE
Invsee++ console Error

### ISSUE THREAD

**Issue by justLxy** [Jannyboy11/InvSee-plus-plus#48]
[03:08:57] [Server thread/WARN]: [InvSee++] Error reading player's save file /home/milk/minecraft/jydlr/./world/playerdata/9e8b9269-721f-3781-a0a3-9ac14b4bfc75-10531114771047373390.dat
java.io.EOFException: null
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?]
	at net.minecraft.nbt.NbtIo.createDecompressorStream(NbtIo.java:49) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:53) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:33) ~[?:?]
	at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:118) ~[InvSee++.jar:?]
	at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:104) ~[InvSee++.jar:?]
	at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.lambda$getAll$2(KnownPlayersProvider.java:53) ~[InvSee++.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.io.EOFException
		at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?]
		at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?]
		at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?]
		at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?]
		at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?]
		at net.minecraft.nbt.NbtIo.createDecompressorStream(NbtIo.java:49) ~[?:?]
		at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:53) ~[?:?]
		at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:33) ~[?:?]
		at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:118) ~[InvSee++.jar:?]
		at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:104) ~[InvSee++.jar:?]
		at com.janboerman.invsee.spigot.impl_1_19_2_R1.KnownPlayersProvider.getAll(KnownPlayersProvider.java:45) ~[InvSee++.jar:?]
		at com.janboerman.invsee.paper.AsyncTabCompleter.lambda$new$1(AsyncTabCompleter.java:40) ~[InvSee++.jar:?]
		at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
		at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
		at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jannyboy11** [comment]
You have a corrupt player save file. There's nothing I can do about that.

**Comment by Jannyboy11** [comment]
Can you confirm the command *does* work when applied to other offline players?

**Comment by Jannyboy11** [comment]
By the way, I'm seeing this error is happening when tabcompleting. Does this actually prevent you from opening the spectator inventory you wanted?

**Comment by Jannyboy11** [comment]
The corrupt player file doesn't even have a valid UUID as its name (9e8b9269-721f-3781-a0a3-9ac14b4bfc75-10531114771047373390), so it's a bogus file just sitting there. You can remove it safely.
