### ISSUE TITLE
1.17.1 Error:

### ISSUE THREAD

**Issue by thiagogebrim13** [Jannyboy11/InvSee-plus-plus#6]
```
[03:04:28 INFO]: thiagogebrim issued server command: /invseeplusplus:inventorysee ChedarBr
[03:04:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'invseeplusplus:inventorysee' in plugin InvSeePlusPlus v0.8-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1258]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1258]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2218) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2029) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2010) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1363) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1296) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1207) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Purpur-1258]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.inventory.InventoryCrafting net.minecraft.world.inventory.ContainerPlayer.n()'
        at com.janboerman.invsee.spigot.impl_1_17_R1.MainNmsInventory.<init>(MainNmsInventory.java:66) ~[?:?]
        at com.janboerman.invsee.spigot.impl_1_17_R1.MainNmsInventory.<init>(MainNmsInventory.java:70) ~[?:?]
        at com.janboerman.invsee.spigot.impl_1_17_R1.InvseeImpl.spectateInventory(InvseeImpl.java:46) ~[?:?]
        at com.janboerman.invsee.spigot.api.InvseeAPI.spectateInventory(InvseeAPI.java:302) ~[?:?]
        at com.janboerman.invsee.spigot.InvseeCommandExecutor.onCommand(InvseeCommandExecutor.java:90) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1258]
        ... 21 more
```

**Comment by Jannyboy11** [comment]
I didn't find the time yet to check compatibility with 1.17.1, but thanks for reporting! I'll fix this issue tonight.

**Comment by Jannyboy11** [comment]
Fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/402640d4eca4ecc2c1d5b0d0a28c6625e715c456
