### ISSUE TITLE
error

### ISSUE THREAD

**Issue by F3F5** [Jannyboy11/InvSee-plus-plus#61]
[22:28:35 WARN]: [InvSee++] Error reading player's save file /server/./world/playerdata/4af075bb-334f-3428-8a5d-388aa22047f1.dat
java.io.EOFException: null
at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:?]
at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:?]
at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:?]
at java.util.zip.GZIPInputStream.init(Unknown Source) ~[?:?]
at java.util.zip.GZIPInputStream.init(Unknown Source) ~[?:?]
at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:18) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at com.janboerman.invsee.spigot.impl_1_12_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:117) ~[?:?]
at com.janboerman.invsee.spigot.impl_1_12_R1.KnownPlayersProvider.readName(KnownPlayersProvider.java:103) ~[?:?]
at com.janboerman.invsee.spigot.impl_1_12_R1.KnownPlayersProvider.lambda$getAll$2(KnownPlayersProvider.java:53) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:875) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:806) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:689) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
at java.lang.Thread.run(Unknown Source) [?:?]
Suppressed: java.io.EOFException

**Comment by F3F5** [comment]
fixed by deleting 3 uuids what says invsee, wtf

**Comment by Jannyboy11** [comment]
I don't think this is a bug. One of your player data files could not be read because it didn't adhere to the NBT format.

**Comment by F3F5** [comment]
i don't changes anything

**Comment by F3F5** [comment]
i fixed this by deleting 3 uuids what says invsee
