### ISSUE TITLE
Internal error issue

### ISSUE THREAD

**Issue by witheredwojak** [Jannyboy11/InvSee-plus-plus#7]
**Still getting internal error issue on 1.17.1:**
![зображення](https://user-images.githubusercontent.com/66310741/125145991-6db01900-e12c-11eb-828b-027d4ef3ba7c.png)
**Using last plugin version (0.10.1) and Airplane core (Spigot fork). Server is running on Ubuntu 20.04.1 LTS and Java 16.**
**Here is a plugins list:**
![зображення](https://user-images.githubusercontent.com/66310741/125146022-8c161480-e12c-11eb-8946-c1c7ecf6effc.png)
**And here is error in console:**
[02:09:40] [Server thread/INFO]: SMP_Admin issued server command: /invsee M0RIT
[02:09:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'invsee' in plugin InvSeePlusPlus v0.10.1-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Airplane-44]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-44]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2243) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2035) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1407) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1385) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1378) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1354) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[patched_1.17.1.jar:git-Airplane-44]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-44]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.inventory.InventoryCrafting net.minecraft.world.inventory.ContainerPlayer.n()'
	at com.janboerman.invsee.spigot.impl_1_17_R1.MainNmsInventory.<init>(MainNmsInventory.java:64) ~[?:?]
	at com.janboerman.invsee.spigot.impl_1_17_R1.MainNmsInventory.<init>(MainNmsInventory.java:68) ~[?:?]
	at com.janboerman.invsee.spigot.impl_1_17_R1.InvseeImpl.spectateInventory(InvseeImpl.java:46) ~[?:?]
	at com.janboerman.invsee.spigot.api.InvseeAPI.spectateInventory(InvseeAPI.java:310) ~[?:?]
	at com.janboerman.invsee.spigot.InvseeCommandExecutor.onCommand(InvseeCommandExecutor.java:90) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-44]
	... 21 more

**Comment by Jannyboy11** [comment]
Try again on the latest version of Airplane. I have no issues on git-Airplane-45.

**Comment by witheredwojak** [comment]
Yep. Now it works. Thank you!
