### ISSUE TITLE
Incompatablility with XClaim

### ISSUE THREAD

**Issue by Kittycraft0** [Jannyboy11/InvSee-plus-plus#75]
Whenever I have one of the two, this plugin or XClaim, they work. However, when I have both, this plugin returns errors:

[10:54:34 INFO]: [InvSee++] Enabling InvSeePlusPlus v0.22.6
[10:54:34 ERROR]: Error occurred while enabling InvSeePlusPlus v0.22.6 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Server.getAsyncScheduler()'
        at com.janboerman.invsee.folia.FoliaScheduler.executeAsync(FoliaScheduler.java:46) ~[InvSee++.jar:?]
        at com.janboerman.invsee.paper.AsyncTabCompleter.<init>(AsyncTabCompleter.java:40) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.setupEvents(InvseePlusPlus.java:165) ~[InvSee++.jar:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:125) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[10:54:34 INFO]: [InvSee++] Disabling InvSeePlusPlus v0.22.6
[10:54:35 INFO]: [XC] Enabling XClaim v1.10.5
[10:54:35 WARN]: [XC] No suitable economy plugin was found

**Comment by Jannyboy11** [comment]
Would you mind updating InvSee++ to the latest version and try again please? https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.22.9

It's likely that the issue will persist, but I did recently change the logic which detects whether InvSee++ runs on Folia. I can only dig to find the cause of the issue this weekend.

**Comment by Jannyboy11** [comment]
Very likely this is a bug in XClaim: https://github.com/WasabiThumb/xclaim/pull/58

**Comment by Jannyboy11** [comment]
Turns out I didn't implement this yet in InvSee++, but I did now. Go grab version 0.23.2 and you're good to go!
