### ISSUE TITLE
Mohist 1.19.2 error

### ISSUE THREAD

**Issue by Surferblue** [Jannyboy11/InvSee-plus-plus#79]
Which version of the plugin do I need to use?
Error occurred while enabling InvSeePlusPlus_Give v0.23.2 (Is it up to date?)
java.lang.RuntimeException: Unsupported CraftBukkit version. Please run on one of [1.8.8, 1.12.2, 1.15.2, 1.16.5, 1.17.1, 1.18.2, 1.19.4, 1.20.1]. Are you running the latest InvSee++_Give?
        at com.janboerman.invsee.spigot.addon.give.Setup.setup(Setup.java:48) ~[?:?]
        at com.janboerman.invsee.spigot.addon.give.GivePlugin.onEnable(GivePlugin.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.19.2-43.2.18-universal.jar%23146!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.19.2-43.2.18-universal.jar%23146!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.19.2-43.2.18-universal.jar%23146!/:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:490) ~[forge-1.19.2-43.2.18-universal.jar%23146!/:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:416) ~[forge-1.19.2-43.2.18-universal.jar%23146!/:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:417) ~[server-1.19.2-20220805.130853-srg.jar%23141!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:344) ~[server-1.19.2-20220805.130853-srg.jar%23141!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23141!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:737) ~[server-1.19.2-20220805.130853-srg.jar%23141!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23141!/:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]

**Comment by Jannyboy11** [comment]
The error message tells you exactky what is wrong. 1.19.2 is unsupported. You can upgrade to Mohist 1.19.4. I don't think there is any older version of InvSee++ that supoprted Mohist 1.19.2 properly.
