### ISSUE TITLE
The folia-supported option in Plugin.yml is not set to true.

### ISSUE THREAD

**Issue by paul0665** [Jannyboy11/InvSee-plus-plus#87]
It works in Folia 1.20.2, but the option isn’t marked as supported.

<details>
	<summary>log</summary>

[22:38:21] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\InvSee++.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\InvSee++.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.Main.main(Main.java:134) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'InvSeePlusPlus v0.24.6' as it is not marked as supporting Folia!
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	... 20 more
[22:38:27] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:38:29] [ServerMain/INFO]: Loaded 7 recipes
[22:38:30] [Server thread/INFO]: Starting minecraft server version 1.20.2
[22:38:30] [Server thread/INFO]: Loading properties
[22:38:30] [Server thread/INFO]: This server is running Folia version git-Folia-"757cb09" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 757cb09 on dev/1.20.2)
[22:38:30] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:38:30] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:38:31] [Server thread/WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[22:38:31] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 12 worker threads, and gen parallelism of 12 threads
[22:38:31] [Server thread/INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 6 tick threads
[22:38:31] [Server thread/INFO]: Default game type: SURVIVAL
[22:38:31] [Server thread/INFO]: Generating keypair
[22:38:31] [Server thread/INFO]: Starting Minecraft server on *:50001
[22:38:31] [Server thread/INFO]: Using default channel type
[22:38:31] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[22:38:31] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[22:38:31] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\InvSee++_Clear.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [InvSeePlusPlus]. Please download and install these plugins to run 'InvSeePlusPlus_Clear'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:518) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:38:31] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\InvSee++_Give.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [InvSeePlusPlus]. Please download and install these plugins to run 'InvSeePlusPlus_Give'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:518) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"757cb09"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
</details>

**Comment by Jannyboy11** [comment]
I disabled support for Folia because its the implementation did not work correctly, and fixing it is a nontrivial task (I know how to do it in theory, but it takes quite a bit of time).

See https://github.com/PaperMC/Folia/issues/144

**Comment by Jannyboy11** [comment]
See this issue too: https://github.com/Jannyboy11/InvSee-plus-plus/issues/58

**Comment by Jannyboy11** [comment]
> will folia ever be revisited?

I still very mich like the idea of it, but unfortunately I have larger priorities in life.
Adding proper Folia support is not a small update.
