### ISSUE TITLE
Can't load in CatServer!

### ISSUE THREAD

**Issue by XuanliChe** [Jannyboy11/InvSee-plus-plus#91]
In the Catserver(1.16.5),it said that: 
[14:07:30] [Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus v0.22.6 (Is it up to date?)
 java.lang.NoClassDefFoundError: com/janboerman/invsee/spigot/impl_1_16_R3/MainNmsContainer
        at com.janboerman.invsee.spigot.Impl_1_16_5.<init>(Setup.java:90) ~[?:?]
        at com.janboerman.invsee.spigot.Setup.setup(Setup.java:31) ~[?:?]
        at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-1d8d6313]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-1d8d6313]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:439) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:345) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.janboerman.invsee.spigot.impl_1_16_R3.MainNmsContainer
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:261) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 14 more
Caused by: java.lang.ClassFormatError: Duplicate method name "func_75145_c" with signature "(Lnet.minecraft.entity.player.PlayerEntity;)Z" in class file com/janboerman/invsee/spigot/impl_1_16_R3/MainNmsContainer
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:124) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 14 more

**Comment by Jannyboy11** [comment]
I added SRG-mapped methods to InvSee++ for 1.16.5 because of this issue: https://github.com/Jannyboy11/InvSee-plus-plus/issues/43
Releases before this change should work on CatServer. Can you try InvSee++ version 0.19.4: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.19.4?

**Comment by Jannyboy11** [comment]
If that one does not work, try this one: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.25.1-Mohist-Catserver-1.16.5

**Comment by XuanliChe** [comment]
OK,thankyou very much
________________________________
发件人: Jan ***@***.***>
发送时间: 2024年1月5日 4:00
收件人: Jannyboy11/InvSee-plus-plus ***@***.***>
抄送: XuanliChe ***@***.***>; Author ***@***.***>
主题: Re: [Jannyboy11/InvSee-plus-plus] Can't load in CatServer! (Issue #91)


If that one does not work, try this one: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.25.1-Mohist-Catserver-1.16.5

―
